-- MySQL Script generated by MySQL Workbench
-- Mon Dec 23 21:43:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accountowner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accountowner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accountowner` DEFAULT CHARACTER SET utf8 ;
USE `accountowner` ;

-- -----------------------------------------------------
-- Table `accountowner`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accountowner`.`Owner` ;

CREATE TABLE IF NOT EXISTS `accountowner`.`Owner` (
  `OwnerId` CHAR(36) NOT NULL,
  `Name` NVARCHAR(60) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Address` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`OwnerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountowner`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accountowner`.`Account` ;

CREATE TABLE IF NOT EXISTS `accountowner`.`Account` (
  `AccountId` CHAR(36) NOT NULL,
  `DateCreated` DATE NOT NULL,
  `AccountType` NVARCHAR(45) NOT NULL,
  `OwnerId` CHAR(36) NOT NULL,
  PRIMARY KEY (`AccountId`),
  INDEX `fk_Account_Owner_idx` (`OwnerId` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Owner`
    FOREIGN KEY (`OwnerId`)
    REFERENCES `accountowner`.`Owner` (`OwnerId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
